github: [kravietz]
ko_fi: devsecops
liberapay: devsecops
custom:
  - "https://etherscan.io/address/0x81281a913472b6edf01098446203FE23173BFbEf"   # Coinbase ETH
  - "https://etherscan.io/address/0xE0fD16684386AF74628bB232B8e6A924871E8039"   # Coinbase DAI
  - "https://www.blockchain.com/btc/address/3DsSkFWsWu6ZWNGN74yqCKpvG1cazGsmu5" # Coinbase BTC

